### ISSUE TITLE
Make "tibble" optional

### ISSUE THREAD

**Issue by pank** [rOpenGov/eurostat#105]
Hi,

The eurostat package is very useful and nice to use.  I notice that `tibble` is used for store returend data.  

I'd personally never encountered of `tibbles` before.  If I use something other than `data.frames `I'd be 
`data.tables`.  

Could `tibble` as the output format perhaps be an optional feature?  I appreciate that it's an enhancement cf. #52, but perhaps less so if one is not already using the "tidyverse"(I think that's what it's called).  Note, I am not sure to what extend the package relies on the output format being `tibble`.

Thanks,
Rasmus

**Comment by antagomir** [comment]
Tibble is a data.frame, and it seems to be the preferred variant of data.frame also in [Hadley's R book](http://r4ds.had.co.nz/introduction-2.html). It is an explicit recommendation from us to use tibbles instead of data.frames. Moreover, tibble can be converted to the traditional variant of data.frame with the as.data.frame() function (and to data.table with as.data.table() I guess). These conversions are short and standardized, and can be easily applied on top of the output, so I would avoid adding complexity in the eurostat package itself.

If there is something with tibble that prevents you from doing things that you do with data.frame that would be interesting to hear. I assume that there are no remarkable limitations since tibble is a form of data.frame

**Comment by antaldaniel** [comment]
If anyone want a data.frame output, just use as.data.frame ( returned_value ).  All usual methods are the same on tibble and data.frame, and tibbles convert directly to data.table, too. Since the tidyverse functions are imported into eurobarometer, there is no loss of efficiency in case the user does not want tibbles.
