### ISSUE TITLE
NEWS not in cran

### ISSUE THREAD

**Issue by jhuovari** [rOpenGov/eurostat#116]
The [eurostat cran page](https://cran.rstudio.com/web/packages/eurostat/) doen't include NEWS file. Why is that?

**Comment by antagomir** [comment]
Thanks for spotting this out. I tried to have a look but do not understand this behavior yet. The NEWS.md file is at the root directory as I think it should; and README.md is showing properly in CRAN. 

I also checked hadley/dplyr pkg and there the NEWS.md is also in root directory as in our case, and visible in CRAN, unlike in our case.

**Comment by cjyetman** [comment]
could it be because there is both a [NEWS](https://github.com/rOpenGov/eurostat/blob/master/NEWS) file and a [NEWS.md](https://github.com/rOpenGov/eurostat/blob/master/NEWS.md) file in the root directory... and CRAN prefers the `NEWS` file?

**Comment by antagomir** [comment]
In fact I added "NEWS" to test if that becomes visible in CRAN. But I did not remove NEWS.md yet since I wasn't sure.. and now as I check this after the latest CRAN update.. it [seems to be there](https://cran.r-project.org/web/packages/eurostat/index.html). So I think NEWS.md can be synced with NEWS (if there are discrepancies) and NEWS.md can be removed. Thanks!
