### ISSUE TITLE
r_pjangrp3

### ISSUE THREAD

**Issue by philipus** [rOpenGov/eurostat#182]
Is that data on NUTS level 3 part of the package ?!

I do not find any table on level Nuts 3 via the query

search_eurostat(pattern="NUTS 3", type="table", fixed=FALSE)

**Comment by antagomir** [comment]
The `search_eurostat` function retrieves the TOC directly from the URL maintained by the Eurostat open data portal itself: [https://ec.europa.eu/eurostat/estat-navtree-portlet-prod/BulkDownloadListing?sort=1&downfile=table_of_contents_en.txt](https://ec.europa.eu/eurostat/estat-navtree-portlet-prod/BulkDownloadListing?sort=1&downfile=table_of_contents_en.txt) and looks for all its contents. 

Not immediately obvious why NUTS 3 is not there (NUTS 2 is), suggestions are welcome.

**Comment by antaldaniel** [comment]
I added a preliminary helper function to deal with some probelms of the NUTS coding on Eurostat products, which were moved to a package that is eventually now on CRAN under the name [regions](http://regions.danielantal.eu/).  I did not harmonize yet the two packages, because there are all sorts of issues coming up. 

I guess that your question relates to the [demo_r_pjangrp3](https://appsso.eurostat.ec.europa.eu/nui/show.do?dataset=demo_r_pjangroup&lang=en) statistics, because it has the most similar name. 

However, the NUTS3 level data (together with NUTS2, NUTS1 and quasi NUTS0 = country) is there: 

> eurostat::get_eurostat ( "demo_r_pjangrp3") %>%
>       regions::validate_nuts_regions() %>%
>      dplyr::filter ( typology == "nuts_level_3" )

If you follow the NUTS2016 definition (see [this vignette](http://regions.danielantal.eu/articles/validation.html)), you will not see the quasi-NUTS3 regions of Albania, North Macedonia, Norway, etc. because they have not officially joined the NUTS system.  You can get it if you choose 

> eurostat::get_eurostat ( "demo_r_pjangrp3") %>%
>       regions::validate_nuts_regions(nuts_year = 2021) %>%
>       dplyr::filter ( typology == "nuts_level_3" )

In which case you will get them, but you will lose some data where the not yet official NUTS2021 definition will change the existing EU member's NUTS2016 region borders. 

The other way to get non-EU countries is to simply filter `nchar(geo) == 5`, because all NUTS3 regions and NUTS3-like non-EU regions have an `NN999` geocode structure.

Of course, if you do not use dplyr, you can also 

>  regions::validate_nuts_regions(
>     dat =  eurostat::get_eurostat ( "demo_r_pjangrp3") 
> )
 ... and filter out those that have `nuts_level_3` in the `typology` column.
