### ISSUE TITLE
Why search_eurostat did not find some existing tables

### ISSUE THREAD

**Issue by sbacelar** [rOpenGov/eurostat#188]
Searching for wastewater tables I used

`query <- search_eurostat("wastewater", type = "table")`

but I did not found a table containing the word "wastewater" that I wanted. I know the code for that table is "env_ww_con" and so to download it I did

`dat <- get_eurostat(id="env_ww_con", time_format="num")`

What is the reason for `search_eurostat` didn't find this last table?

**Comment by antagomir** [comment]
The reason is that "env_ww_con" is of type "dataset" whereas you are using the filter type="table" in your `search_eurostat` command. You are missing the desired id because it does not pass the filters that you have set in the function call. Trying `search_eurostat("wastewater", type = "all")` or `search_eurostat("wastewater", type = "dataset")` does return it.
