### ISSUE TITLE
 Error: No such process   in get_eurostat_dic()

### ISSUE THREAD

**Issue by antaldaniel** [rOpenGov/eurostat#227]
I am getting an error from get_eurostat_dic() which is in fact caused by the dependency readr::read_tsv

 ```
dict <- readr::read_tsv(url(tname), 
                            col_names = c("code_name", "full_name"),
                            col_types = readr::cols(.default = readr::col_character()))
```

The url to the function call is a well-formatted url that can be opened in a browser:
https://ec.europa.eu/eurostat/estat-navtree-portlet-prod/BulkDownloadListing?file=dic%2Fen%2Fdimlst.dic

The error message is not very helpful: 
Error: No such process  

And I think that it is not caused by read_tsv but url, which is not explicitly imported into this function.  Any ideas what is this?

**Comment by pitkant** [comment]
Hi! Could you provide a reproducible example of what you were trying to do along with the contents of `sessionInfo()`? 

I tested `get_eurostat_dic()` with an up-to-date development version of eurostat-package using built-in function example `tmp <- get_eurostat_dic("crop_pro")` and it worked fine for me.

**Comment by antaldaniel** [comment]
@pitkant I just wanted to say I am working on something that gives a more general solution to some problems with get_eurostat_dic.  Since the initial release of eurostat the Eurostat website and the API changed a bit, and I think that there could be a better way to handle labels.

**Comment by pitkant** [comment]
Great! Maybe along with a few other fixes (updated datasets, get_eurostat_geospatial make_valid parameter) these changes could be rolled into one minor (3.7.10 -> 3.8 ?) CRAN release. Can you create a PR when you're done?

**Comment by pitkant** [comment]
It seems that the new SDMX 2.1 endpoint for downloading codelists does not include dimlst (and table_dic) files and some kind of workaround has to be done anyway.

**Comment by pitkant** [comment]
While this issue was about the error message and not the availability / non-availability of retrieved .dic files I will continue to remark that I received a reply from Eurostat user support that stated that:

"At the end of the transition phase some files will not be produced anymore and /dic/{en,fr,de} will not exist (codelists files). Nevertheless, there will be the option to retrieve all codelists in XML and to retrieve the inventory listing of codelists." (I gather that inventory listing of codelists means these dimlst and table_dic files)

Currently test_06_label section that is utilising internal helper functions that retrieve dimlst and table_dic fail but I will have to look at the code a bit and see if these are really necessary.

**Comment by pitkant** [comment]
References to old style dimlst.dic and table_dic.dic removed from code and tests. Closed with the CRAN release of package version 4.0.0
