### ISSUE TITLE
Automated builds fail

### ISSUE THREAD

**Issue by antagomir** [rOpenGov/eurostat#248]
See discussion in PR #246

**Comment by espinielli** [comment]
The Bulk Download Guidelines [1] in section 2.2.2 reference a file which is used in the
[definition of `label_eurostat_vars`](https://github.com/rOpenGov/eurostat/blob/master/R/label_eurostat.R#L230)

> The complete list of 'code lists' can be found in the file ‘Dimlst.dic’

The [relevant link](https://ec.europa.eu/eurostat/estat-navtree-portlet-prod/BulkDownloadListing?sort=1&downfile=dic%2Fen%2Fdimlst.dic) in the PDF gives an error:

> File dimlst.dic does not exist or is not readable on the server
<img width="1048" alt="Screenshot 2022-12-30 at 11 15 20" src="https://user-images.githubusercontent.com/891692/210059493-2dd3a239-4ff8-4450-8312-8bbed0da5e34.png">

In fact there is no such file `dimlst.dic` in the `dic/en` _folder_.

I signalled this missing file on Eurostat website...



[1] https://ec.europa.eu/eurostat/estat-navtree-portlet-prod/BulkDownloadListing?sort=1&file=BulkDownload_Guidelines.pdf

**Comment by antagomir** [comment]
This might be related to ongoing transitioning from Eurostat Bulk Download to API #243 ...

**Comment by espinielli** [comment]
I tried and manually downloaded the new code list from the new bulk data download service [1].
The downloaded file, `ESTAT_downloads_29367ce1-3661-49d2-8674-c96aa93038bd.zip`, is zipped and the internal single file, `Full_Items_List_EN.txt`, is a TSV dataset (despite the `.txt` extension 😒 ).
I have faked the `dic_df <- get_eurostat_dic(dic, lang = lang)` call in `label_eurostat()` to use this file where 
I have taken (and renamed) the `Code` (-> `code_name`) and `Label` (-> `full_name`) columns.

The `test_06_label.R` test then works 🎉 🎊 . 

Now it is just 😄 a matter to see how to implement the automatic file download: from checking the choreography in the DevTools console, it is a matter of 
1. POSTing to https://ec.europa.eu/eurostat/databrowser-backend/api/bulk/1.0/LIVE/export/codeListItems in order to get the `uuid`
2. then GETting to https://ec.europa.eu/eurostat/databrowser-backend/api/bulk/1.0/LIVE/export/download/bulk/<uuid>
But maybe there is a simpler way...(and should this be retrieved on every single call or cached [with reasonable expiration])

[1] https://ec.europa.eu/eurostat/databrowser/bulk?lang=en
