### ISSUE TITLE
check_access_to_data broken?

### ISSUE THREAD

**Issue by minemR** [rOpenGov/eurostat#266]
https://ec.europa.eu/eurostat/cache/GISCO/distribution/v2/nuts/geojson/NUTS_RG_60M_2006_4326_LEVL_0.geojson
is no longer available?

**Comment by pitkant** [comment]
The most likely explanation would seem to be that the GISCO site is temporarily unavailable.

**Comment by majazaloznik** [comment]
Looks like they are back online

**Comment by pitkant** [comment]
@majazaloznik thanks for reporting! We will try to improve our error messages to be more indicative when the problem is a server issue or when it is due to something else.

**Comment by minemR** [comment]
In this case just the link tested in `check_access_to_data` wasn't working, everything that I tested was working. So maybe this link also should be updated/changed to something more relevant?

**Comment by pitkant** [comment]
Ah, thanks for explanation @minemR . It's now working so I'm not sure what the issue was there.

There seems to be a redirect from the URL in the function

```
http_url <- "https://ec.europa.eu/eurostat/cache/GISCO/distribution/v2/nuts/geojson/NUTS_RG_60M_2006_4326_LEVL_0.geojson"
```

to 

https://gisco-services.ec.europa.eu/distribution/v2/nuts/geojson/NUTS_RG_60M_2006_4326_LEVL_0.geojson

so maybe that partly contributed to the function not working while everything else did.
