### ISSUE TITLE
get_eurostat_raw fails with the id sts_inppd_m

### ISSUE THREAD

**Issue by iNANOV** [rOpenGov/eurostat#303]
Hello,

The **get_eurostat**  function fails with the download of  **sts_inppd_m** Eurobase table.  It did work 7 days ago. 

`get_eurostat("sts_inppd_m")
Dataset query already saved in cache_list.json...
Error in get_eurostat("sts_inppd_m") : 
  get_eurostat_raw fails with the id sts_inppd_m`

**Comment by iNANOV** [comment]
Thank you for the advice, it works with pre filtering.

**Comment by pitkant** [comment]
Good to hear. I'm sure Eurostat folks also prefer that people pre-filter their queries rather than getting full datasets and filtering them locally out of habit. 

Still, some issues might be harder to solve with just filtering and we will have to explore solutions on how to solve these problems. I will close this issue but leave the other one open.
