### ISSUE TITLE
JSON error

### ISSUE THREAD

**Issue by antagomir** [rOpenGov/eurostat#58]
> prod <- get_eurostat("sts_inpr_a", filters = list(geo = "AT"))
Error in get_eurostat_json(id, filters, type = type, stringsAsFactors = stringsAsFactors,  : 
  Failure to get data. Status code: 416

    "sts_inpr_a" stands for Short-TermBusinessStatistics_IndustryProduction_annual
    Without the filters argument, it works perfectly fine

**Comment by jhuovari** [comment]
The query exceeds maximum limits, that's why it gives an error. However, the error code should be 500. With that there is a proper error message. I don't know why 416.

There is, after all, also a bug. That data can not be properly filtered as nace_r2 filtering have to be included and `names(filters) <- gsub("[0-9]", "", names(filters))` in `eurostat_json_url` changes nace_r2 to nace_r. 

But, there must be some reason for that code. I can not figure out what it was. Just removing it would likely produce an other bug.

**Comment by jhuovari** [comment]
`prod <- get_eurostat("sts_inpr_a", filters = list(geo = "AT"))` gives still an error as it exceeds Eurostat limits and you have to use `get_eurostat` without filters. More limited query with filters should now work.

What still bit mystery is why the error code is 416. I think it should be 500.
