### ISSUE TITLE
Graphic unclear

### ISSUE THREAD

**Issue by claireINRS** [rOpenGov/eurostat#95]
I try to vizualise the number of fatal accidents by countries.
The result is not clear. Did I forget something in the code?

```
library(eurostat)
library(knitr)
library(ggplot2)

id<-search_eurostat("fatal")
#id<-search_eurostat("fatal")$code
kable(id)

## Téléchargement des données
clean_eurostat_cache()
EUROPE<-get_eurostat("hsw_aw_fnms",time_format="num")
kable(head(EUROPE))

## Visualisation graphique
ggplot(EUROPE,aes(x=time,y=values,colour=geo))+geom_line()

```

[Fatal accidents by geo.pdf](https://github.com/rOpenGov/eurostat/files/1179862/Fatal.accidents.by.geo.pdf)

**Comment by antagomir** [comment]
I am not sure what you are after in this analysis, and what you expect the figure look like but the code is working correctly. The figure is what it is because each year has several data points for each country (see the other columns in `EUROPE` (as can be seen by browsing through the data frame). Perhaps you are willing to select a particular subset based on age/nace_r1 etc. variables, or to sum over these within each country. But these are analyttical operations that depend on your specific needs and package itself does not provide any default solutions in such cases.

**Comment by claireINRS** [comment]
Thanks for your answer.
I expected a graph like the one attached.
Maybe it comes from the data.

[tsdtr420.pdf](https://github.com/rOpenGov/eurostat/files/1179949/tsdtr420.pdf)

**Comment by antagomir** [comment]
Yes I think the data is different. Perhaps this latter figure is drawn with data that has exactly one number per year/country combination. But dificult to say for sure without seeing the data.

**Comment by pbiecek** [comment]
It's unclear because you have all severities and age groups pulled together
filter them out (example below) or use as faceting variables
```
ggplot(dplyr::filter(EUROPE, severity == "FAT", age == "TOTAL"),
       aes(x=time,y=values,colour=geo))+geom_line() +
  scale_y_log10()
```
